# Generated by Django 5.0.3 on 2024-03-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tahun_terbit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.buku')),
                ('peminjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.peminjam')),
            ],
        ),
        migrations.AddField(
            model_name='buku',
            name='penulis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.penulis'),
        ),
    ]
