# Generated by Django 5.0.3 on 2024-03-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buku',
            options={'verbose_name_plural': '2. Buku'},
        ),
        migrations.AlterModelOptions(
            name='peminjam',
            options={'verbose_name_plural': '3. Peminjam'},
        ),
        migrations.AlterModelOptions(
            name='peminjaman',
            options={'verbose_name_plural': '4. Peminjaman'},
        ),
        migrations.AlterModelOptions(
            name='penulis',
            options={'verbose_name_plural': '1. Penulis'},
        ),
    ]
